---
- name: Check Zabbix agent port 10050 on all hosts
  hosts: web:zabbix-server:kibana:elasticsearch:bastion
  gather_facts: no
  vars:
    zabbix_port: 10050

  tasks:
    - name: Проверка доступности порта 10050
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ zabbix_port }}"
        timeout: 5
      register: result

    - name: Вывод результата
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ 'OK' if result.elapsed < 5 else 'FAILED' }}"
