- name: Удаление Zabbix Agent
  hosts: web:kibana:elasticsearch
  become: true
  tasks:
    - name: Остановка zabbix-agent
      systemd:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Остановка zabbix-agent2
      systemd:
        name: zabbix-agent2
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Удаление пакета zabbix-agent
      apt:
        name: zabbix-agent
        state: absent
        purge: yes

    - name: Удаление пакета zabbix-agent2
      apt:
        name: zabbix-agent2
        state: absent
        purge: yes

    - name: Удаление конфигурации Zabbix Agent (если осталась)
      file:
        path: /etc/zabbix
        state: absent
