[bastion]
bastion ansible_host=46.21.246.37 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[web]
s1.ru-central1.internal ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.21.246.37'
s2.ru-central1.internal ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.21.246.37'

[zabbix-server]
zabbix.ru-central1.internal ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.21.246.37'

[kibana]
kibana.ru-central1.internal ansible_host=158.160.106.229 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.21.246.37'

[elasticsearch]
elastic.ru-central1.internal ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@46.21.246.37'
