
---
- name: Configure Zabbix Agent 2 via zabbix-release package
  hosts: web:kibana:elasticsearch:bastion
  become: yes
  vars:
    zabbix_version: "7.0"
    ubuntu_version: "24.04"

  tasks:
    - name: Скачивание пакета zabbix-release
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb"
        dest: "/tmp/zabbix-release.deb"

    - name: Установка пакета zabbix-release
      apt:
        deb: "/tmp/zabbix-release.deb"
        state: present

    - name: Обновление кэша пакетов
      apt:
        update_cache: yes

    - name: Установка Zabbix Agent 2
      apt:
        name:
          - zabbix-agent2
        state: present
        force: yes

    - name: Копируем конфигурацию
      template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
      notify: restart zabbix-agent2

    - name: Проверяем запущен ли Zabbix Agent 2
      service:
        name: zabbix-agent2
        state: started
        enabled: yes

  handlers:
    - name: restart zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted
